/** Declaration file generated by dts-gen */

export = gulp_electron;

declare function gulp_electron(options: any): any;

declare namespace gulp_electron {
    const prototype: {
    };

}

